### Health Check
GET http://127.0.0.1:3010/health

###
### Get All Users
GET http://127.0.0.1:3010/users

###
### Get User by ID
GET http://127.0.0.1:3010/users/1

###
### Create New User
POST http://127.0.0.1:3010/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com"
}

###
### Update User
PATCH http://127.0.0.1:3010/users/1
Content-Type: application/json

{
    "countryCode": "US",
    "nationalNumber": "1234567890"
}

###
### Update User Email
PATCH http://127.0.0.1:3010/users/1
Content-Type: application/json

{
    "firstName": "Jane",
    "email": "jane.doe@example.com"
}

###
### Disable User
PATCH http://127.0.0.1:3010/users/disable/1

###
### Enable User
PATCH http://127.0.0.1:3010/users/enable/1

###
### Delete User
DELETE http://127.0.0.1:3010/users/1

### 